### ISSUE TITLE
Create a tech-blog

### ISSUE THREAD

**Issue by agluszak** [vanbinhstudios/thelegendofericc#24]
We could write posts about our development struggles (@fiffeek's been kinda already doing it)

**Comment by agluszak** [comment]
@fiffeek, can we have separate blog on github.io and project description in readme?

**Comment by fiffeek** [comment]
Everything is set up now, but I do not have time to make the entire site myself:
-> README.md is here https://vanbinhstudios.github.io/thelegendofericc/
-> docs (or blog) is here https://vanbinhstudios.github.io/thelegendofericc/index.md
